# tomcat.yml
---
- hosts: zabix-box
  sudo: yes
  
  vars:
      mysql_root_pass: "password"
      zabix_db: "zabix"
      db_user: "zabix"
      db_user_pass: "zabix"
      
  tasks:
  
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
    
    - name: Apt update
      apt:
        update_cache: yes
        
    - name: Install php7.0
      apt: name={{item}} state=present
      with_items:
        - php7.0-bcmath
        - php7.0-xml
        - php7.0-mbstring
           
    - name: Install a zabix.deb package from the internet.
      apt:
      deb: http://repo.zabbix.com/zabbix/3.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.5-1+xenial_all.deb
      
    - name: Apt update
      apt:
        update_cache: yes
    
    - name: Install Zabbix Server with MySQL
      apt: name={{item}} state=present
      with_items:
        - zabbix-server-mysql
        - zabbix-frontend-php
        - zabbix-agent
    
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: "{{zabix_db}}"
        state: present

    - name: Add deploy DB user and allow access to news_* databases
      mysql_user: name={{db_user}} password={{db_user_pass}} host="%" priv={{zabix_db}}.*:ALL,GRANT state=present
  
    - name: Import the initial schema and data
      shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -p {{db_user_pass}}   
  
