# tomcat.yml
---
- hosts: zabix-box
  sudo: yes
  
  vars:
      mysql_root_pass: "password"
      zabix_db: "zabix"
      db_user: "zabix"
      db_user_pass: "zabix"
      
  tasks:
  
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
    
    - name: Apt update
      apt:
        update_cache: yes
        
    - name: Install php7.0
      apt: name={{item}} state=present
      with_items:
        - php7.0-bcmath
        - php7.0-xml
        - php7.0-mbstring
           
    - name: Install a zabix.deb package from the internet.
      apt:
      deb: http://repo.zabbix.com/zabbix/3.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.5-1+xenial_all.deb
      
    - name: Apt update
      apt:
        update_cache: yes
    
    - name: Install Zabbix Server with MySQL
      apt: name={{item}} state=present
      with_items:
        - zabbix-server-mysql
        - zabbix-frontend-php
        - zabbix-agent
        
    - name: Crate databases    
      shell: mysql --password="{{mysql_root_pass}}" --user=root -e "CREATE DATABASE "{{ zabix_db }}" CHARACTER SET utf8 COLLATE utf8_bin"
      ignore_errors: True
      
    - name: Create user MySQL
      shell: mysql --password="{{mysql_root_pass}}" --user=root -e "CREATE USER '"{{ db_user }}"'@'localhost' IDENTIFIED BY '"{{ db_user_pass }}"'"
      ignore_errors: True
      
    - name: Add access to database
      shell: mysql --password="{{mysql_root_pass}}" --user=root -e "GRANT ALL PRIVILEGES ON "{{ zabix_db }}".* TO '"{{ db_user }}"'@'localhost'"
      ignore_errors: True
      
    - name: FLUSH PRIVILEGES
      shell: mysql --password="{{mysql_root_pass}}" --user=root -e "FLUSH PRIVILEGES;"
      
    - name: Import the initial schema and data
      shell: zcat /usr/share/zabbix-server-mysql/{schema,images,data}.sql.gz |mysql -u"{{ db_user }}" -p"{{ db_user_pass }}" "{{ zabix_db }}"   
      ignore_errors: True
      
    - name: CP zabix server conf
      template: src=/vagrant/files/zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf
      
    - name: CP zabix apache2 conf 
      template: src=/vagrant/files/apache.conf.j2 dest=/etc/zabbix/apache.conf
    
    - name: CP zabix conf php to /etc/zabbix/
      template: src=/vagrant/files/zabbix.conf.php.j2 dest=/etc/zabbix/zabbix.conf.php
      
    - name: CP to apache2/conf-enabled
      template: src=/vagrant/files/zabbix.conf.j2 dest=/etc/apache2/conf-enabled/zabbix.conf
      
    - name: Apache a2enmod alias
      shell: a2enmod alias
       
    - name: Restart service apache2, in all cases
      systemd:
        state: restarted
        daemon_reload: yes
        name: apache2
    
    - name: Restart service zabbix-server, in all cases
      systemd:
        state: restarted
        daemon_reload: yes
        name: zabbix-server

    - name: enable service zabbix-server and ensure it is not masked
      systemd:
        name: zabbix-server
        enabled: yes

      
      
      
      
