
Vagrant.configure("2") do |config|
    config.vm.define "zabix-dev" do |zabix_box|
    zabix_box.vm.box = "ubuntu/xenial64"
    zabix_box.vm.hostname = 'zabix-dev'
    zabix_box.vm.box_url = "ubuntu/xenial64"
    zabix_box.vm.network :private_network, ip: "192.168.56.50"
	zabix_box.vm.provision "shell", path: "vagrant_provision_scripts/zabbix_ubuntu.sh"
#    zabix_box.vm.provision "ansible_local" do |ansibleconf|
#      ansibleconf.playbook = "./ansible/zabix.yml"
#    end
    zabix_box.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1000]
      v.customize ["modifyvm", :id, "--name", "zabix-dev"]
    end
  end
end
