
Vagrant.configure("2") do |config|
  config.vm.define "ansible-box" do |ansible_box|
    ansible_box.vm.box = "ubuntu/xenial64"
    ansible_box.vm.hostname = 'ansible-box'
    ansible_box.vm.box_url = "ubuntu/xenial64"

    ansible_box.vm.network :private_network, ip: "192.168.56.150"
	  ansible_box.vm.provision "shell", path: "provision_ssh_key.sh"
    ansible_box.vm.provision "shell", path: "provision_ansible.sh"
#    ansible_box.vm.provision "shell", path: "python-minimal.sh"
    ansible_box.vm.provision "shell", path: "update_upgade.sh"
#    ansible_box.vm.provision :ansible do |ansible|
#      ansible.playbook = "playbook.yml"
#    end
    ansible_box.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4000]
      v.customize ["modifyvm", :id, "--name", "ansible-box"]
    end
  end

  config.vm.define "one-box" do |one_box|
    one_box.vm.box = "ubuntu/xenial64"
    one_box.vm.hostname = 'one-box'
    one_box.vm.box_url = "ubuntu/xenial64"

    one_box.vm.network :private_network, ip: "192.168.56.151"
	  one_box.vm.provision "shell", path: "provision_ssh_key.sh"
    one_box.vm.provision "shell", path: "python-minimal.sh"
    one_box.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 256]
      v.customize ["modifyvm", :id, "--name", "one-box"]
    end
  end
  config.vm.define "art-box" do |one_box|
    one_box.vm.box = "ubuntu/xenial64"
    one_box.vm.hostname = 'art-box'
    one_box.vm.box_url = "ubuntu/xenial64"

    one_box.vm.network :private_network, ip: "192.168.56.152"
    one_box.vm.provision "shell", path: "provision_ssh_key.sh"
    one_box.vm.provision "shell", path: "python-minimal.sh"
    one_box.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "art-box"]
    end
  end
  config.vm.define "git-box" do |one_box|
    one_box.vm.box = "ubuntu/xenial64"
    one_box.vm.hostname = 'git-box'
    one_box.vm.box_url = "ubuntu/xenial64"

    one_box.vm.network :private_network, ip: "192.168.56.153"
    one_box.vm.provision "shell", path: "provision_ssh_key.sh"
    one_box.vm.provision "shell", path: "python-minimal.sh"
    one_box.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 256]
      v.customize ["modifyvm", :id, "--name", "git-box"]
    end
  end
end
