# git.yml
---
- hosts: git
  sudo: yes
  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Install GIT-CORE
      apt:
        name: git-core
        state: present

    - user:
        name: git
        shell: /bin/bash
        groups: adm
        append: yes

    - name: Copy pub key
      shell: mkdir -p /home/git/.ssh && cat /home/ubuntu/.ssh/id_rsa.pub >> /home/git/.ssh/authorized_keys
